### ISSUE TITLE
netflix web gui is not opening

### ISSUE THREAD

**Issue by manasranpanda** [Netflix/vector#114] opened 2016-03-15 11:03 UTC
Hi As I have einstalled pmdaapache with port no 80 and the webpage is not opening. any suggestion.

**Comment by spiermar** [comment] 2016-03-15 15:37
@manasranpanda Not sure if I understood it correctly. You had pcp running and was accessing Vector via pmwebd? And after installing pmdaapache it stopped working?

**Comment by manasranpanda** [comment] 2016-03-15 17:23
Dear Martin,

Thanks you for your reply. Please find below bullet points:


1.        I had the PCP installed and its working with vector frame work. Its also exposing the application matrices to single web page for single system by giving the hostname/IP. The question is that can we monitor multiple system at a time in same web page.

2.       As I checked with forum and found the some users are opening the web gui by using url: http://<hostname>:8080<http://%3chostname%3e:8080>, where the monitor page is displayed. Is it show if then please guide me.

I was guessing that pmdaapache will work same as apache web page and trying to configure but the page was not opening. I have configured the pmdaapache with port no:80, where apache2 is also avialble in same system with different port.


Thanks,
Manas

**Comment by spiermar** [comment] 2016-03-15 17:44
These are separate issues.

1. No, Vector was designed to monitor a single host at a time. There is feature request to monitor multiple hosts (https://github.com/Netflix/vector/issues/37), but we're still evaluating what would be the best way of implementing this. Having said that, nothing prevents you from opening multiple tabs to monitor different hosts.

2. I'm not aware of anything like you described, but you can provide the hostname:port to be monitored in the URL. e.g.: http://<vector_url>/#/?host=<hostname_being_monitored>&hostspec=localhost

3. pmdaapache is the agent module that provides Apache server metrics, not a web server itself. @natoscott can correct me if I'm wrong, but that's my understanding.

**Comment by fche** [comment] 2016-03-15 17:51
> pmdaapache is the agent module that provides Apache server metrics, not a web server itself

Definitely.

**Comment by natoscott** [comment] 2016-03-15 21:06
@spiermar yep that's correct, pmdaapache(1) provides the apache.* metrics.
@manasranpanda have a read of the man page at http://www.pcp.io/man/man1/pmdaapache.1.html - especially the -p option and the required Apache configuration to enable apache metrics, and the "installation" section - this allows you to monitor apache itself, if that's what you were attempting?

**Comment by manasranpanda** [comment] 2016-03-16 01:45
Dear frank and Martin,

Thanks a lot to you both.

Regards,
Manas

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by spiermar** [comment] 2016-03-16 02:15
I'm assuming this was solved. Closing the issue. Let me know if otherwise.

**Closed by spiermar** 2016-03-16 02:15 UTC

**Comment by manasranpanda** [comment] 2016-03-16 04:51
Dear Scott,

As you mentioned we can monitor on apache web server, can you please provide the steps to do so because I am not finding anything on provided URL.

Thanks,
Manas

**Comment by natoscott** [comment] 2016-03-16 05:06
@manasranpanda it's a two stage process:
1. enable Apache's "ExtendedStatus" metrics (described in DESCRIPTION section of http://www.pcp.io/man/man1/pmdaapache.1.html) via httpd.conf or equivalent, and restart Apache;
2. Run the ./Install script for the Apache PCP PMDA (as described in INSTALLATION section of http://www.pcp.io/man/man1/pmdaapache.1.html)

"pminfo -f apache" should then show you the metrics and their current values

**Comment by manasranpanda** [comment] 2016-03-16 05:10
Thanks Scott,

This is already configured and I am able to see the metrics by executing “pminfo -f apache”. My question is the can we see same metrics on web page as graph, which is a apache web page.

Thanks,
Manas

**Comment by natoscott** [comment] 2016-03-16 05:15
@manasranpanda oh, sorry - I misunderstood your question - I'll leave that one for @spiermar but I believe you'd need to create a custom Vector view for those metrics.

**Comment by manasranpanda** [comment] 2016-03-16 05:18
Thanks Scott for the information and for your support.

As I said earlier, the vector frame work is also working fine for me.

Thanks,
Manas

**Comment by fche** [comment] 2016-03-16 11:08
> My question is the can we see same metrics on web page as graph, which is a apache web page.

Vector does brief histories of live data.  For more formal historical graphs with PCP, one would need to run a pmlogger - configured to record the apache.* metrics in addition to its defaults.  Then one would need to run pmwebd and its bundled graphite/grafana webapps to interactively build dashboard graphs for those metrics.  That should result in a graphite-flavoured URL similar to

http://localhost:44323/graphite/render?target=*.apache.*&from=-2d&until=now&format=png&width=1027&height=245

to return a PNG graphics object.

**Comment by spiermar** [comment] 2016-03-16 15:29
@manasranpanda you should be able to get those metrics into the Vector front-end, but it will require adjusting some configuration files.

This is a similar issue to https://github.com/Netflix/vector/issues/110. Let me know if this doesn't solve your problem.

Also, I'm on Slack in case you have more questions. http://slack.vectoross.io/

**Comment by manasranpanda** [comment] 2016-03-21 04:25
Dear Martin,

Can you please let me know about below details:


-          Active Active PCP backend. What type of load balancing required ?

-          How PCP backend detail is supplied to PCP client ? DHCP or ACS ?

-          Active Active PCP Vector. What type of load balancing required ?

-          Message/Data flow – How metrics is passed to PCP backend

o   How Vector fetches data from PCP backend


-          Is there any DB involved in PCP backend ? Can multiple PCP shared same DB ?

-          How to collect custom metrics – example number of OVS flows

Thanks,
Manas

**Comment by fche** [comment] 2016-03-21 16:53
For a general introduction to PCP, please see the books, e.g.:
http://www.pcp.io/books/PCP_UAG/html-single/

If you still have general questions, please consider posing them on the mailing list, instead of this bug tracking system.

**Comment by manasranpanda** [comment] 2016-03-21 17:19
Thanks for your mail. Can you please send me the mailing list wher I can put our questions as this ID: pcp@oss.sgi.com (pcp@oss.sgi.com)<mailto:pcp@oss.sgi.com> is not working.

**Comment by fche** [comment] 2016-03-21 17:22
The mailing list is up & running in general.  If you can't figure out what's wrong between you and that server, please supply more details than "not working".

**Comment by manasranpanda** [comment] 2016-03-21 17:25
Please find the attachment.

**Comment by manasranpanda** [comment] 2016-04-22 06:23
Dear Team,

Please let me know is there any DB can be involved in PCP backend? If so please let me know the procedure to implements the same. And one more ask can multiple PCP shared in same DB?

Please respond as I was trying to send mail via : pcp@oss.sgi.com<mailto:pcp@oss.sgi.com> and got a notice as delivered failed.

Thanks,
Manas

**Comment by spiermar** [comment] 2016-04-22 15:32
Delivery probably failed because you need to sign up for the mail list.

http://oss.sgi.com/mailman/listinfo/pcp
