### ISSUE TITLE
multi-host monitoring

### ISSUE THREAD

**Issue by rvernica** [Netflix/vector#37] opened 2015-04-16 17:40 UTC
I am not sure this is the intent of the project, but my initial experience with Vector has been very pleasant and I am looking into ways to use it for multiple host monitoring.

More exactly, imagine a situation where dozens or hundreds of hosts need to be monitored for critical metrics. Time-line graphs probably won't work, so I am imagining a graph showing the hosts on the X axis and the most recent reading of the metric on the Y axis.

Could I somehow use Vector for this use case? As a side note, do you have any pointers to something that could be used to achieve this (preferably with PCP)? Thanks!

**Comment by fche** [comment] 2015-04-16 17:42
I'm hoping that work on issue #2 will be a big first step toward this.  It would give a user interface to the already-existing possibility of having a single pmwebd talk to an arbitrary reachable pmcd (not just on its localhost).  Extending that capability to individual charts vs. a global setting would probably satisfy this issue.

**Comment by fche** [comment] 2015-04-16 17:43
By the way, see also the graphite & grafana webapps available with pcp.  Those already draw multi-host graphs (based upon multi-host archives collected on the server, such as via pmmgr).

**Comment by spiermar** [comment] 2015-04-16 18:21
The way Vector was designed was based on our need to monitor single instances independently. We have other monitoring tools that deal with cluster-level aggregation and persistence, so it was never a requirement.
Issue #2 that @fche mentioned would allow Vector to use a "central" pmwebd to get metrics from different hosts (other than localhost), but still not combine metrics from multiple hosts.
Technically it would be possible (and not that complex) to add a multi-host feature to Vector. I would not be against it, as long as the UI is kept simple and clean.
If there's interest, I'm happy to add that to the pipeline! Also, if you have implemented something, feel free to submit a pull request!

**Comment by pforai** [comment] 2015-04-16 21:22
@spiermar is Atlas the project that can do that from the same data as Vector gets?

**Comment by rvernica** [comment] 2015-04-20 22:02
@pforai Is the Atlas you are referring to? https://atlas.hashicorp.com/help 

> Atlas is one foundation to manage and provide visibility to your servers, containers, VMs, configuration management, service discovery, and additional operations services.

**Comment by pforai** [comment] 2015-04-20 22:04
Nope, I was referring to https://github.com/Netflix/atlas.

**Comment by schrepfler** [comment] 2015-05-03 22:35
Yes, it would be nice to specify if/where Vector overlaps with Atlas. Would using Atlas mean Vector is not needed?

**Comment by as-martin** [comment] 2017-01-06 17:49
Maybe grafana app can help in this case.

**Comment by spiermar** [comment] 2017-06-22 19:29
Closing since this is out of scope.

**Closed by spiermar** 2017-06-22 19:29 UTC
Labels: review
