### ISSUE TITLE
Broken chart rendering

### ISSUE THREAD

**Issue by rfrht** [Netflix/vector#76] opened 2015-07-31 19:49 UTC
Hello,

I just rebased my Vector to the current HEAD version (71f235f0c0), and I've found that it broke the chart rendering.

The bottom part of the chart is clipped. See a [sample image](http://i.imgur.com/TqR5YWz.png)
The previous release (which I downloaded circa June 11) doesn't have this problem. See a [screenshot](http://i.imgur.com/ZlrVhuR.png).

I'm using 64-bit Linux Firefox, version 38.1

Thanks a lot!

**Comment by spiermar** [comment] 2015-07-31 20:12
That seems to be a missing height property on the chart. There were some updates to the charts and the height configuration. I can't reproduce the issue here, but before I try on other systems, can you try to force refresh all assets, clean and update all dependencies?

**Comment by spiermar** [comment] 2015-09-14 16:42
Assuming it's working now. Closing the issue, but please re-open it if needed.

**Closed by spiermar** 2015-09-14 16:42 UTC
